name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Codecov upload 
      uses: codecov/codecov-action@v2
      
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: |
          3.1.x
          5.0.x
        
    - name: Restore dependencies
      run: dotnet restore Calculator/Calculator.sln
      
    - name: Build
      run: dotnet build Calculator/Calculator.sln --configuration Release --no-restore
      
    - name: Test
      run: dotnet test Calculator/Calculator.sln --configuration Release --no-build --verbosity normal 
      
    - name: Code Coverage
      run: dotnet test Calculator/Calculator.sln --collect:"XPlat Code Coverage" --results-directory ./coverage
